name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # FRONTEND
    - name: Install frontend deps
      working-directory: numero_front
      run: npm install

    - name: Run frontend tests
      working-directory: numero_front
      run: npm test  

    - name: Build frontend
      working-directory: numero_front
      run: npm run build

    # BACKEND
    - name: Install backend deps
      working-directory: numero_backend
      run: npm install

    - name: Build backend
      working-directory: numero_backend
      run: npm run build  

    - name: Run backend tests
      working-directory: numero_backend
      run: npm test
