name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build frontend (optional)
        run: |
          cd numero_front
          npm ci
          npm run build

      - name: Deploy to EC2 frontend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_FRONT }}
          username: ${{ secrets.EC2_USER_FRONT }}
          key: ${{ secrets.EC2_KEY_FRONT }}
          script: |
            cd ~/numero_tma/numero_front
            if ! swapon --show | grep -q '/swapfile'; then
              echo "Creating swap file..."
              sudo fallocate -l 2G /swapfile
              sudo chmod 600 /swapfile
              sudo mkswap /swapfile
              sudo swapon /swapfile
            else
              echo "Swap file already exists."
            fi
            git pull origin main
            npm ci
            NODE_OPTIONS="--max-old-space-size=4096" npm run build
            sudo systemctl restart nginx
