name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Check that backend builds correctly
        run: |
          cd numero_backend
          npm ci
          npm run build

      - name: Deploy to EC2 backend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_BACK }}
          username: ${{ secrets.EC2_USER_BACK }}
          key: ${{ secrets.EC2_KEY_BACK }}
          script: |
           cd ~/numero_tma/numero_backend
           git fetch origin main
           git reset --hard origin/main
           rm -rf node_modules
           npm ci || npm install --legacy-peer-deps
           NODE_OPTIONS="--max-old-space-size=4096" npm run build || { echo "Build failed"; exit 1; }
           sudo pm2 restart numero_backend --update-env || sudo pm2 start dist/server.js --name numero_backend -f
           sudo pm2 save

